### PR TITLE
Copy project configuration file during project generation

### PR DESCRIPTION
**Pull request by csjall**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-custom-device-wizard/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

This PR adds another code generation step that copies a project configuration file that redirect VeriStand assemblies.

### Why should this Pull Request be merged?

Without the project configuration file the project will generate a build error when building. The only way to cleanly build a user must otherwise manually link to the correct VeriStand assembly version.

### What testing has been done?

Generated a custom device using the wizard and compile all configurations of the project.

### CODE REVIEW

**Comment by dnattinger** [comment]
> * `NIVS_Consolidated_CDW_MetaDataObj.lvclass:Common.vi`: Since the path is always constant and not reading from any other code, I would prefer using a path constant instead of Strip Path and a string constant. `Build Path` will accept a path constant. Much easier to read _..\..\Null.lvproj.config_ than what currently exists.

I agree with this feedback, Build Path with a path constant and ..\ values is always better than Strip Paths and a file name string constant.

**Comment by buckd** [comment]
image

**Comment by dnattinger** [comment]
Hopefully the feedback on this review will motivate both of y'all to go kudo this post on the LabVIEW Idea Exchange if you haven't already: https://forums.ni.com/t5/LabVIEW-Idea-Exchange/Make-It-More-Obvious-that-Build-Path-Can-Accept-a-Relative-Path/idi-p/1697728

**Comment by buckd** [comment]
> Hopefully the feedback on this review will motivate both of y'all to go kudo this post on the LabVIEW Idea Exchange if you haven't already: https://forums.ni.com/t5/LabVIEW-Idea-Exchange/Make-It-More-Obvious-that-Build-Path-Can-Accept-a-Relative-Path/idi-p/1697728

Done

**Pull request merged**
